from filestorage import FileItem as FileItem, FilterBase as FilterBase
from typing import Any, Callable

def random_string_generator(filename: str) -> str: ...

class RandomizeFilename(FilterBase):
    async_ok: bool = ...
    name_generator: Any = ...
    def __init__(self, name_generator: Callable[[str], str] = ...) -> None: ...
