from filestorage import FileItem as FileItem, FilterBase as FilterBase
from filestorage.exceptions import (
    FileExtensionNotAllowed as FileExtensionNotAllowed,
)
from typing import Any, List

class ValidateExtension(FilterBase):
    async_ok: bool = ...
    extensions: Any = ...
    def __init__(self, extensions: List[str]) -> None: ...
    def extension_allowed(self, ext: str) -> bool: ...
    def filename_allowed(self, filename: str) -> bool: ...
