from filestorage import (
    AsyncStorageHandlerBase as AsyncStorageHandlerBase,
    FileItem as FileItem,
    StorageHandlerBase as StorageHandlerBase,
)
from typing import Any, Tuple

class DummyHandler(StorageHandlerBase):
    files: Any = ...
    last_save: Any = ...
    last_save_contents: bytes = ...
    last_delete: Any = ...
    validated: bool = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def get_file_key(self, item: FileItem) -> FileItem: ...
    def assert_exists(self, filename: str, path: Tuple[str, ...]) -> None: ...
    def assert_file_contains(
        self, filename: str, path: Tuple[str, ...], data: bytes
    ) -> None: ...

class AsyncDummyHandler(AsyncStorageHandlerBase, DummyHandler):
    allow_async: bool = ...
    def get_file_key(self, item: FileItem) -> FileItem: ...
    def assert_exists(self, filename: str, path: Tuple[str, ...]) -> None: ...
    def assert_file_contains(
        self, filename: str, path: Tuple[str, ...], data: bytes
    ) -> None: ...
