import abc
from . import utils as utils
from typing import Any, BinaryIO, NamedTuple, Optional, Tuple

class SyncReader(BinaryIO, metaclass=abc.ABCMeta):
    data: Any = ...
    filename: Any = ...
    def __init__(self, item: FileItem) -> None: ...
    def seek(self, offset: int, whence: int = ...) -> int: ...
    def read(self, size: int = ...) -> bytes: ...
    closed: bool = ...

class FileItem(NamedTuple):
    filename: str
    path: Tuple[str, ...] = ...
    data: Optional[BinaryIO] = ...
    content_type: Optional[str] = ...
    @property
    def has_data(self) -> bool: ...
    @property
    def url_path(self) -> str: ...
    @property
    def fs_path(self) -> str: ...
    def get_content_type(self) -> Optional[str]: ...
    def copy(self, **kwargs: Any) -> FileItem: ...
    def __enter__(self): ...
    def __exit__(*args: Any, **kwargs: Any) -> None: ...
    def sync_read(self, size: Optional[int] = ...) -> bytes: ...
    async def async_read(self, size: Optional[int] = ...) -> bytes: ...
    def sync_seek(self, offset: int) -> int: ...
    async def async_seek(self, offset: int) -> int: ...
