from . import utils as utils
from typing import Any, BinaryIO, NamedTuple, Optional, Tuple

class FileItem(NamedTuple):
    filename: str
    path: Tuple[str, ...] = ...
    data: Optional[BinaryIO] = ...
    @property
    def url_path(self) -> str: ...
    @property
    def fs_path(self) -> str: ...
    def copy(self, **kwargs: Any) -> FileItem: ...
    def sync_read(self, size: Optional[int] = ...) -> bytes: ...
    async def async_read(self, size: Optional[int] = ...) -> bytes: ...
    def sync_seek(self, offset: int) -> int: ...
    async def async_seek(self, offset: int) -> int: ...
